language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "gomint-github"
  artifacts:
    paths:
      - ./gomint-server/target/GoMint.jar

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
